<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: lelab
 * Date: Sat, 08 Mar 2014 12:46:32 -0500
 */

$conf['title'] = 'Le Lab Mastering - Wiki';
$conf['lang'] = 'fr';
$conf['template'] = 'bootstrap';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['plugin']['authmysql']['TablesToLock'] = array();

// end auto-generated content
